### ISSUE TITLE
No need for the vercel function

### ISSUE THREAD

**Issue by dustinrouillard** [JoshHeng/JackboxProxy#1]
While it's cool, it's not required, you just have to understand a bit more about how they had the API hosted.

It's hosted using AWS Load Balancers, which use CNAME records on the DNS side, so you can just grab the CNAME and set the host in the fetch request.

Here is a [standalone cloudflare worker](https://gist.github.com/dustinrouillard/872210160c95ae88e3664b78f93b1bbb) attached in this gist is two javascript files.

`jackbox-proxy-with-ecast.js` - Proxies both the ecast api and the frontend
`jackbox-proxy.js` - Proxies only the frontend (has the exact same effect to the user)

However, during more testing there is absolutely no need to proxy the ecast api (it's on a different host already) as the only point of this proxy should be to have users go to a different domain, and stay on that domain during the game, of course on some sites their API is cors protected, meaning you would have to proxy it, this one however is not and you only need to proxy the frontend for everything else to work.

Sharing this simply to show how I've done it without the unnecessary vercel function. _(no matter how much I love vercel haha)_

**Comment by JoshHeng** [comment]
Hello!

The reason I've used the Vercel proxy was because I couldn't get Cloudflare Workers to work properly with the API. If you'd like to submit a PR that would fix this, you'd be welcome to - however I won't be able to get around to implementing this myself for a while.

Thank you!

**Comment by dustinrouillard** [comment]
Sure, I'll submit a PR with the changes, just wanted to see if the interest was there with the issue first, of course you should test them yourself just to be sure it works the same way yours does for you as well.
